name: Build arm64

on:
  push:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    concurrency:
        group: ${{ github.head_ref }}-arm64
        cancel-in-progress: true
    steps:
      - uses: actions/checkout@v2
        with:
          repository: xmake-io/xmake
          submodules: true

      - name: Build and package
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: >
            bash -c
            "apt update &&
            apt install make gcc ruby -y &&
            gem install fpm &&
            cd /github/workspace/xmake &&
            ./scripts/makepkg deb || true"
            
      - name: Upload
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          ls -l
          pwd
          git add .
          git commit -m "Upload xmake v$(curl -s https://api.github.com/repos/xmake-io/xmake/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')" 
          git push
