name: Build

on:
  push:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up multiarch/qemu-user-static
        run: |
          docker run --rm --privileged multiarch/qemu-user-static:register --reset

      - uses: docker://multiarch/ubuntu-core:arm64-bionic
        with:
          args: >
            bash -c
            "apt update &&
            apt install make gcc git ruby -y &&
            gem install fpm &&
            cd /github/workspace &&
            git clone --recursive https://github.com/xmake-io/xmake.git &&
            cd ./xmake &&
            ./scripts/makepkg deb || true &&
            mv ./*.deb ../ &&
            rm -rf xmake"

      - uses: docker://multiarch/ubuntu-core:armhf-bionic
        with:
          args: >
            bash -c
            "apt update &&
            apt install make gcc git ruby -y &&
            gem install fpm &&
            cd /github/workspace &&
            git clone --recursive https://github.com/xmake-io/xmake.git &&
            cd ./xmake &&
            ./scripts/makepkg deb || true &&
            mv ./*.deb ../ &&
            rm -rf xmake"
            
      - name: Upload
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Upload xmake v$(curl -s https://api.github.com/repos/xmake-io/xmake/releases/latest | grep -oP '"tag_name": "\K(.*)(?=")' | tr -d 'v')" 
          git push
